trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
    - job: build

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          cd gui
          npm install
          npm run build
        displayName: 'npm install and build'

      - task: CopyFiles@2
        displayName: 'Copy Files'
        inputs:
          SourceFolder: 'gui/build'
          TargetFolder: '$(build.artifactstagingdirectory)'
          CleanTargetFolder: true

      - task: PublishBuildArtifacts@1      
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          ArtifactName: 'build'