trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: build

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        cd gui
        npm install
        npm run build
      displayName: 'npm install and build'

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: 'gui/build'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true

    - task: PublishPipelineArtifact@1     
      inputs:
        TargetPath: '$(build.artifactstagingdirectory)'
        ArtifactName: 'build'

  - deployment: deploy
    dependsOn: build
    environment: S3
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.7'
          - script: |
              pip install awscli
              aws configure list
              aws s3 sync $(System.ArtifactsDirectory) s3://wikidata-fuzzy-search
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)